[Settings]
  ID = "commonhealth-data-map"

[build]
  base    = "."
  publish = "build"
  command = "./scripts/cibuild"
  environment = { YARN_VERSION = "1.22.4", YARN_FLAGS = "--frozen-lockfile" }

[[redirects]]
  from = "/data/*"
  to = "/data/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
